CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS order_items (
    id SERIAL PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    item INTEGER NOT NULL
);